JWK_LoadoutConfig {
 m_aSlots {
  JWK_LoadoutSlotConfig "{65F4A88D930AC7A9}" {
   m_iType HEADWEAR
   m_fSkipChance 0
   m_aChoices {
    "{01277905A781CDF4}Prefabs/Characters/HeadGear/BERET/beret_Bleu_Fonce_Infanterie.et"
   }
  }
  JWK_LoadoutSlotConfig "{65F4A88D936E279C}" {
   m_iType SHIRT
   m_aChoices {
    "{7326973EDED9139D}Prefabs/Characters/Uniforms/F3_Ubas/CE/F3_Ubas_Rolled_CE_Caporal.et"
   }
  }
  JWK_LoadoutSlotConfig "{65F4A88D935A1540}" {
   m_iType PANTS
   m_aChoices {
    "{ADBA42284222F1BA}Prefabs/Characters/Uniforms/F3_Pantalon/F3_Pantalon_CE.et"
   }
  }
  JWK_LoadoutSlotConfig "{65F4A88D90881426}" {
   m_iType FOOTWEAR
   m_aChoices {
    "{253C75176D3BF9A4}Prefabs/Characters/Footwear/Haix_Sable_Base.et"
   }
  }
  JWK_LoadoutSlotConfig "{65F4A88D90F5DE54}" {
   m_iType BACKPACK
  }
 }
 m_aWeaponSets {
  JWK_LoadoutWeaponsSetConfig "{65F4A88DB0044DAF}" {
   m_sId "HK416F"
   m_aItems {
    JWK_LoadoutItemConfig "{658ED3C0E3F30807}" {
     m_iStoragePurpose PURPOSE_WEAPON_PROXY
     m_sPrefab "{21DEDBF890CAE897}Prefabs/Weapons/Rifles/HK416F/HK416F-S_AimM5.et"
    }
    JWK_LoadoutItemConfig "{658ED3C12FAF9DB3}" {
     m_iStoragePurpose PURPOSE_DEPOSIT
     m_sPrefab "{1AEFE527061C0141}Prefabs/Weapons/Magazines/STANAG/Magazine_556x45_HK_30rnd_BO_BT_F5.et"
     m_iAmount 3
    }
   }
  }
  JWK_LoadoutWeaponsSetConfig "{65F4A88DB07F90B7}" {
   m_sId "FAMAS"
   m_aItems {
    JWK_LoadoutItemConfig "{658ED3C0CB42F32B}" {
     m_iStoragePurpose PURPOSE_WEAPON_PROXY
     m_sPrefab "{01E7BB9FCA17084A}Prefabs/Weapons/Rifles/FAMAS/Famas_F1_Inf_RIS.et"
    }
    JWK_LoadoutItemConfig "{6590B634A954ABBB}" {
     m_iStoragePurpose PURPOSE_DEPOSIT
     m_sPrefab "{4BD8473ECB6C950B}Prefabs/Weapons/Magazines/FAMAS/Magazine_556x45_SS109_Famas_25rnd_BT.et"
     m_iAmount 3
    }
   }
  }
  JWK_LoadoutWeaponsSetConfig "{65F4A88DB1A87D11}" {
   m_sId "Handgun_Glock17"
   m_aItems {
    JWK_LoadoutItemConfig "{658ED3C1151D459B}" {
     m_iStoragePurpose PURPOSE_WEAPON_PROXY
     m_sPrefab "{163B4015946457A5}Prefabs/Weapons/Handguns/Glock17/Handgun_Glock17.et"
    }
    JWK_LoadoutItemConfig "{6590B6345F3ABD3D}" {
     m_iStoragePurpose PURPOSE_DEPOSIT
     m_sPrefab "{613B7C0EF0DCFB60}Prefabs/Weapons/Magazines/GLOCK/Magazine_9x19_Glock17_17rnd_Base.et"
     m_iAmount 4
    }
   }
   m_iType BASIC
  }
  JWK_LoadoutWeaponsSetConfig "{6FFEC0DEFA100001}" {
   m_sId "Handgun_PAMAS"
   m_aItems {
    JWK_LoadoutItemConfig "{6FFEC0DEFA100011}" {
     m_iStoragePurpose PURPOSE_WEAPON_PROXY
     m_sPrefab "{1DD725B7BD47576F}Prefabs/Weapons/Handguns/PAMAS/PAMAS_G1.et"
    }
    JWK_LoadoutItemConfig "{6FFEC0DEFA100012}" {
     m_iStoragePurpose PURPOSE_DEPOSIT
     m_sPrefab "{9C05543A503DB80E}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_Ball.et"
     m_iAmount 4
    }
   }
   m_iType BASIC
  }
  JWK_LoadoutWeaponsSetConfig "{6FFEC0DEFA100002}" {
   m_sId "Handgun_PAMAC50"
   m_aItems {
    JWK_LoadoutItemConfig "{6FFEC0DEFA100021}" {
     m_iStoragePurpose PURPOSE_WEAPON_PROXY
     m_sPrefab "{695B2CF2DE7B5235}Prefabs/Weapons/Handguns/PAMAC50/Handgun_PAMAC50_base.et"
    }
    JWK_LoadoutItemConfig "{6FFEC0DEFA100022}" {
     m_iStoragePurpose PURPOSE_DEPOSIT
     m_sPrefab "{4B5ACD71BC632979}Prefabs/Weapons/Magazines/PAMAC50/Magazine_9x19_MAC50_9rnd_Base.et"
     m_iAmount 4
    }
   }
   m_iType BASIC
  }
 }
}
