SCR_PlaceableEntitiesRegistry {
 m_sAddon "FFREMIXEDPVE"
 m_Prefabs {
  "{6FFEC0DEF1A00001}Prefabs/Vehicles/AlliedAMF/FFRX_GBC180_Transport.et"
  "{6FFEC0DEF1A00002}Prefabs/Vehicles/AlliedAMF/FFRX_GBC180_Cargo.et"
  "{6FFEC0DEF1A00007}Prefabs/Vehicles/AlliedAMF/FFRX_GBC180_Arsenal.et"
  "{6FFEC0DEF1A00008}Prefabs/Vehicles/AlliedAMF/FFRX_GBC180_Ammo.et"
  "{6FFEC0DEF1A00009}Prefabs/Vehicles/AlliedAMF/FFRX_GBC180_Repair.et"
  "{6FFEC0DEF1A0000A}Prefabs/Vehicles/AlliedAMF/FFRX_GBC180_Tanker.et"
  "{6FFEC0DEF1A0000B}Prefabs/Vehicles/AlliedAMF/FFRX_GBC180_Command.et"
  "{6FFEC0DEF1A00003}Prefabs/Vehicles/AlliedAMF/FFRX_VBL.et"
  "{6FFEC0DEF1A00004}Prefabs/Vehicles/AlliedAMF/FFRX_VBL_MAG58.et"
  "{6FFEC0DEF1A00005}Prefabs/Vehicles/AlliedAMF/FFRX_Griffon.et"
  "{6FFEC0DEF1A00006}Prefabs/Vehicles/AlliedAMF/FFRX_VBCI.et"
 }
}
