JWK_SpeechConfig {
 m_aBanks {
  JWK_SpeechBankConfig "{65A0CEBE934533D2}" : "{D5BD7A421747EA47}Configs/Speech/Banks/SpeechBank_Default.conf" {
  }
  JWK_SpeechBankConfig "{6584AA25870E405B}" : "{44FEDB90D45E0C19}Configs/Speech/Banks/SpeechBank_Passphrases.conf" {
  }
  JWK_SpeechBankConfig "{6584AA25F4FC7908}" : "{BA0C570117D1FB88}Configs/Speech/Banks/SpeechBank_Player.conf" {
  }
  JWK_SpeechBankConfig "{6652A0161EE66EB7}" : "{65F1C28B51112FE9}Configs/Speech/Banks/SpeechBank_PlayerActions.conf" {
  }
  JWK_SpeechBankConfig "{BE6A3C0E24B1EB0A}" : "{D90FFE66D2D9EB91}Configs/Speech/Banks/SpeechBank_MCD_Player.conf" {
  }
 }
}
