JWK_SpeechConfig {
 m_aBanks {
  JWK_SpeechBankConfig "{663CB0CD0494ED9E}" : "{D5BD7A421747EA47}Configs/Speech/Banks/SpeechBank_Default.conf" {
  }
  JWK_SpeechBankConfig "{65DF49DF4DB94041}" : "{7AB3553EE2637C29}Configs/Speech/Banks/SpeechBank_AmbientCivilian.conf" {
  }
  JWK_SpeechBankConfig "{7ED001C6C621A69B}" : "{783CBB2C5ADC8668}Configs/Speech/Banks/SpeechBank_MCD_AmbientCivilian.conf" {
  }
 }
}
