SCR_MissionHeader : "{64B2F8D8059EE270}Missions/FreedomFighters/Everon.conf" {
 World "{0E15D706E35C9455}Worlds/FFANIZAY.ent"
 m_sName "FF REMIXED - PVE - Anizay"
 m_sDescription "Un conflit vivant, évolutif et inconnu au départ."\
 ""\
 ""
 m_sDetails "La reconnaissance et le renseignement débloquent la carte. L'économie de guerre et la logistique rythment la progression. L'état-major pilote les opérations. Des campagnes tournantes, une nouvelle carte chaque trimestre."
 m_iPlayerCount 40
}