JWK_SpeechBankConfig {
 m_aSamples {
  JWK_SpeechSampleConfig "{5CB0A416454A947D}" {
   m_sName "CIV_GREET_01"
   m_iSignal 129
   m_sSubtitleText "#MCD-Speech-Player-CivGreet01"
  }
  JWK_SpeechSampleConfig "{A4F90E4E01FACA6B}" {
   m_sName "CIV_GREET_02"
   m_iSignal 130
   m_sSubtitleText "#MCD-Speech-Player-CivGreet02"
  }
  JWK_SpeechSampleConfig "{EE5F7FD6B794C0C1}" {
   m_sName "CIV_GREET_03"
   m_iSignal 131
   m_sSubtitleText "#MCD-Speech-Player-CivGreet03"
  }
  JWK_SpeechSampleConfig "{F47079F3E1FC1FAB}" {
   m_sName "CIV_ASK_PRESENCE_01"
   m_iSignal 132
   m_sSubtitleText "#MCD-Speech-Player-CivAskPresence01"
  }
  JWK_SpeechSampleConfig "{DB9EABFC8C5359C7}" {
   m_sName "CIV_ASK_PRESENCE_02"
   m_iSignal 133
   m_sSubtitleText "#MCD-Speech-Player-CivAskPresence02"
  }
  JWK_SpeechSampleConfig "{C4D93EACEC8244DD}" {
   m_sName "CIV_ASK_PRESENCE_03"
   m_iSignal 134
   m_sSubtitleText "#MCD-Speech-Player-CivAskPresence03"
  }
  JWK_SpeechSampleConfig "{CD000000000AB030}" {
   m_sName "CIV_ASK_HELP_01"
   m_iSignal 135
   m_sSubtitleText "#MCD-Speech-Player-CivAskHelp01"
  }
  JWK_SpeechSampleConfig "{CD000000000AB031}" {
   m_sName "CIV_ASK_HELP_02"
   m_iSignal 136
   m_sSubtitleText "#MCD-Speech-Player-CivAskHelp02"
  }
  JWK_SpeechSampleConfig "{CD000000000AB032}" {
   m_sName "CIV_ASK_HELP_03"
   m_iSignal 137
   m_sSubtitleText "#MCD-Speech-Player-CivAskHelp03"
  }
 }
}
