JWK_AddonIntegrationConfig {
 m_aFactionAddons {
  JWK_ModFactionAddons "{69EB0505049F012E}" {
   m_aTargetFactionKeys {
    "USSR"
   }
   m_aAddVehicles {
    "{77683C4167CB572D}Prefabs/Vehicles/EnemyTF/FFRX_BM21_Grad.et"
    "{E07095C9F153B11F}Prefabs/Vehicles/EnemyTF/FFRX_TIGR_AGS17.et"
    "{3E198415CE15DF27}Prefabs/Vehicles/EnemyTF/FFRX_TIGR_Arbalet.et"
    "{107F34E25D045FE9}Prefabs/Vehicles/EnemyTF/FFRX_TIGR_KORD.et"
    "{E1073A73475D2E29}Prefabs/Vehicles/EnemyTF/FFRX_TIGR_PKM.et"
    "{CBF0E9C7453538CB}Prefabs/Vehicles/EnemyTF/FFRX_TIGR_Recon.et"
    "{76FA566A32C88883}Prefabs/Vehicles/EnemyTF/FFRX_TIGR_Unarmed.et"
   }
  }
 }
}